# Generated by Django 4.2.8 on 2023-12-12 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=10, null=True)),
                ('repository_link', models.CharField(blank=True, max_length=100, null=True)),
                ('last_commit', models.CharField(blank=True, max_length=10, null=True)),
                ('vulnerabilities', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.BooleanField(blank=True, null=True)),
                ('upload_date', models.DateField(default=django.utils.timezone.now)),
                ('last_scan', models.DateField(blank=True, null=True)),
                ('src_code', models.FileField(upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
