# Generated by Django 4.2.8 on 2023-12-12 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vdetection', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
