# Generated by Django 4.2.8 on 2023-12-12 19:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Vdetection', '0002_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('repository_link', models.CharField(max_length=100)),
                ('last_commit', models.CharField(max_length=10)),
                ('vulnerabilities', models.PositiveIntegerField()),
                ('status', models.BooleanField()),
                ('upload_date', models.DateField(default=datetime.datetime(2023, 12, 12, 19, 1, 37, 370092, tzinfo=datetime.timezone.utc))),
                ('last_scan', models.DateField()),
                ('src_code', models.FileField(upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
