# Generated by Django 4.2.8 on 2023-12-12 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vdetection', '0004_alter_project_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='last_commit',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='last_scan',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='repository_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='vulnerabilities',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
